### ISSUE TITLE
为何每次获取到的 textLayout.numberOfGlyphs 都是固定数值

### ISSUE THREAD

**Issue by Meonardo** [Arcovv/TextKit-Tutorial#1]
首先, 这不是个 issue, 
我想请教一下, 为什么每次获取到的 `textLayout.numberOfGlyphs` 都是固定数值, 且这个数值 == `fullContent().count`, 这意味着所有的 `textView` 填充的都是同一份数据吗?(试着打印一下 `textView.text` 确实如此)
多谢!

**Comment by Arcovv** [comment]
glyphs 是字形的意思，當 textStorage 把 textLayout 加進來的時候，就已經知道這個 storage 有多少 glyphs 了，fullContent() 返回的是 String。在一半情況下字元數量應該和自省數量相等。
